apiVersion: v1
kind: Service
metadata:
  name: {{ template "stolon.proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "stolon.name" . }}
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "stolon-proxy"
    heritage: "{{ .Release.Service }}"
spec:
  {{ if .Values.proxy.serviceType }}
  type: {{ .Values.proxy.serviceType }}
  {{ end }}
  ports:
    - port: {{ .Values.ports.externalPort }}
      targetPort: {{ .Values.ports.internalPort }}
  selector:
    app: {{ template "stolon.name" . }}
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "stolon-proxy"
    stolon-cluster: {{ template "stolon.clusterName" . }}
