{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "stolon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - endpoints
    - configmaps
  verbs:
    - "*"
{{- end -}}
